name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t my-image .
      
      - name: Test image for vulnerabilities
        run: |
          # Use Docker Scout or other vulnerability scanning tool
          docker scout my-image

      - name: Check vulnerability scan results
        run: |
          # Use a script or command to check vulnerability scan results
          # If no high vulnerabilities found, proceed with image publishing
          # If high vulnerabilities found, exit with a non-zero code

      - name: Publish Docker image to GitHub Packages
        if: success()
        run: |
          echo "$CR_PAT" | docker login ghcr.io -u USERNAME --password-stdin
          docker tag my-image ghcr.io/USERNAME/my-image:latest
          docker push ghcr.io/USERNAME/my-image:latest
